### ISSUE TITLE
Wrong securityheaders.enabled option in readme

### ISSUE THREAD

**Issue by mrflix** [bnomei/kirby3-security-headers#38]
Thank you Bruno for providing this awesome plugin!

In the readme it says to use `'bnomei.securityheaders.enable' => true,` to enable the security headers in the local environment. That didn't work for me. Turns out it's `'bnomei.securityheaders.enabled' => 'force',`.

**Comment by bnomei** [comment]
the `force` option is gone in plugin version 5+

**Comment by bnomei** [comment]
for consistency with other plugins it also got renamed from `enable` to `enabled`
